### ISSUE TITLE
Roadmap [BR]

### ISSUE THREAD

**Issue by Sazzo** [Sazzo/Logger#1]
Agora:
- [ ]  Colocar no ar no server do pastebin.
- [ ]  Fazer deploy na heroku e configurar o domínio.
- [ ]  Iniciar o Projeto do Bot
- [ ]  Implementar os comandos e eventos.
- [ ]  Se tudo der certo, fazer deploy na heroku e publicar no top.gg (Discord Bot List)
